### ISSUE TITLE
python3: can't open file 'mtprotoproxy.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dlisin** [alexbers/mtprotoproxy#133]
I am using following `docker-compose` file to run mtprotoproxy
```
version: '3'
services:
  proxy:
    image: alexbers/mtprotoproxy:stable
    restart: always
    network_mode: "host"
    ports:
      - 443:443
    volumes:
      - /home/dlisin/mtproto-proxy/config.py:/home/tgproxy/config.py
```

Everything was ok, until today. 
Now both `latest` and `stable` docker images failing with following error:
```
proxy_1       | python3: can't open file 'mtprotoproxy.py': [Errno 2] No such file or directory
proxy_1       | python3: can't open file 'mtprotoproxy.py': [Errno 2] No such file or directory
proxy_1       | python3: can't open file 'mtprotoproxy.py': [Errno 2] No such file or directory
```
