### ISSUE TITLE
how to use prometheus for logs

### ISSUE THREAD

**Issue by TahaPY** [alexbers/mtprotoproxy#146]
how i can use prometheus to get network traffic of my proxy??

**Comment by alexbers** [comment]
what do you mean by the network traffic? The Prometheus is a tool to collect metrics

**Comment by shraik** [comment]
Нужен пример конфига для получения статистики в формате prometeus. И по какому URL забирать статистику. Например как в MTG http://x.x.x.x:3129/prometheus/

**Comment by alexbers** [comment]
например можно в config.py дописать:
```
METRICS_PORT = 32560
METRICS_WHITELIST = ["118.42.147.91", "15.43.51.164"]
```

а в конфиге prometheus что-то такое:
```
  - job_name: mtprotoproxy
    dns_sd_configs:
      - names:
        - 'tg.myhostname.com'
        type: "A"
        port: 32560
```

путь стандартный
